/**
 * Language packs — everything that changes when a family speaks a
 * different language lives behind this interface: kinship terms, the
 * lunar calendar's display names, nakshatra/gotra lists, and the few UI
 * strings that carry native script.
 *
 * The kinship *logic* (Dravidian classificatory rules — generation,
 * side, cross/parallel, seniority) is shared by every pack; a pack only
 * supplies the words. The English gloss for each relationship is
 * generated by the engine itself and is identical across packs.
 */
import type { LunarMonth, Tithi } from '../../types/family';

/** A term spelled bilingually. `native` is absent in the English pack. */
export interface BiTerm {
  en: string;
  native?: string;
}

/**
 * Native-script kinship vocabulary. Slot names describe the relationship
 * the engine computed; "of*" slots are the genitive sibling forms used in
 * composed terms ("<elder brother's> son"). Composed and either/or forms
 * ("father's brother — elder or younger unknown") are built by the engine
 * from these atoms.
 */
export interface KinshipTerms {
  /** Respectful second person — the badge for one's own record. */
  you: string;

  father: string;
  mother: string;
  son: string;
  daughter: string;
  /** Gender-unknown child, for composed forms. */
  childGeneric: string;
  husband: string;
  wife: string;
  stepFather: string;
  stepMother: string;

  brotherElder: string;
  brotherYounger: string;
  brotherGeneric: string;
  sisterElder: string;
  sisterYounger: string;
  sisterGeneric: string;
  siblingGeneric: string;

  /** Genitive forms: "<slot> son" must read naturally in the language. */
  ofBrotherElder: string;
  ofBrotherYounger: string;
  ofBrotherGeneric: string;
  ofSisterElder: string;
  ofSisterYounger: string;
  ofSisterGeneric: string;

  /**
   * Cross cousins (a parent's opposite-gender sibling's children).
   * Telugu uses one male term for both ages; Kannada splits by
   * seniority — so the schema splits, and packs may repeat a word.
   */
  crossCousinMaleElder: string;
  crossCousinMaleYounger: string;
  crossCousinFemaleElder: string;
  crossCousinFemaleYounger: string;

  fatherElderBrother: string;
  fatherYoungerBrother: string;
  fatherSister: string;
  motherBrother: string;
  motherElderSister: string;
  motherYoungerSister: string;

  grandfather: string;
  grandmotherPaternal: string;
  grandmotherMaternal: string;
  greatGrandfather: string;
  greatGrandmother: string;
  grandparentGeneric: string;

  grandson: string;
  granddaughter: string;
  greatGrandson: string;
  greatGranddaughter: string;
  grandchildGeneric: string;

  /** A sister's child to a man, a brother's child to a woman. */
  crossNephew: string;
  crossNiece: string;

  sonInLaw: string;
  daughterInLaw: string;

  /** Spouses of one's siblings and cousins, by the sibling's seniority. */
  siblingWifeElder: string;
  siblingWifeYounger: string;
  sisterHusbandElder: string;
  sisterHusbandYounger: string;

  nieceHusband: string;
  nephewWife: string;
  granddaughterHusband: string;
  grandsonWife: string;

  /** In-laws through one's own spouse. */
  spouseFather: string;
  spouseMother: string;
  spouseBrotherElder: string;
  spouseBrotherYounger: string;
  spouseBrotherGeneric: string;
  spouseSisterElder: string;
  spouseSisterYounger: string;
  spouseSisterGeneric: string;

  ancestor: string;
  descendant: string;
  relative: string;
  relativeByMarriage: string;
}

/** Display names for the lunar (chandramana) calendar. */
export interface CalendarTerms {
  months: Record<LunarMonth, BiTerm>;
  tithis: Record<Tithi, string>;
  /** Fortnight labels, e.g. Telugu convention Suddha/Bahula. */
  paksha: { shukla: string; krishna: string };
  /** Field labels for the date editor. */
  labels: { masa: string; paksha: string; tithi: string };
}

export interface TraditionTerms {
  /** Field label as this community says it: 'Gotram' vs 'Gotra'. */
  gotraLabel: string;
  nakshatraLabel: string;
  /** The 27 birth stars, traditional order. */
  nakshatras: BiTerm[];
  /** Common gotras — deliberately not exhaustive; free typing allowed. */
  gotras: BiTerm[];
}

export interface LanguagePack {
  id: string;
  /** BCP-47 tag of the native script ('te', 'kn'); absent = English only. */
  langTag?: string;
  /** Human name used in form labels: "Name (Telugu)". */
  languageName?: string;
  /** Absent in the English pack — badges then show the gloss alone. */
  kinship?: KinshipTerms;
  calendar: CalendarTerms;
  tradition: TraditionTerms;
  ui: {
    /** Hint under the "family born into" field, in local words. */
    maidenHint: string;
  };
}
