/**
 * Kinship — "who is this person to me?"
 *
 * Telugu and Kannada follow the Dravidian kinship system, which is
 * *classificatory*: terms are generated by rule, not memorised
 * per-relative. Four things decide the word:
 *
 *   1. generation offset — is this person my parent's generation, mine,
 *      my children's?
 *   2. side — paternal or maternal. Mother's brother and father's
 *      younger brother are both "uncle" in English, never in Telugu.
 *   3. cross vs parallel — my father's *brother's* children are
 *      siblings; his *sister's* children are cross cousins. The line
 *      historically decided who one could marry.
 *   4. seniority — elder brother vs younger brother, father's elder
 *      vs younger brother.
 *
 * Because the system is classificatory, the same terms extend outward:
 * a parent's cousin is addressed like a parent's sibling, a cousin's
 * child like a sibling's child. So we compute the shape of the path and
 * derive the term, rather than enumerating relationships.
 *
 * The rules live here; the words live in the language pack
 * (src/lib/lang/). The English gloss is generated alongside and is the
 * same whichever pack is active.
 *
 * Every path through a family graph has the form
 *     [spouse] parent^up child^down [spouse]
 * which is what makes this tractable.
 */
import type { FamilyData, Person, PersonId, Union } from '../types/family';
import type { KinshipTerms, LanguagePack } from './lang';
import { pack as activePack } from '../family.config';
import { parentUnionOf, unionsAsPartner } from './graph';

export interface Kinship {
  /** Native-script term, e.g. 'మేనత్త'. Absent for the english pack. */
  native?: string;
  /** Plain-English gloss, e.g. "father's sister". */
  en: string;
  /** True when we had to describe rather than name the relationship. */
  approximate?: boolean;
}

type Step = 'parent' | 'child' | 'spouse';

interface Hop {
  step: Step;
  person: Person;
}

const MAX_DEPTH = 8;

/** Build a Kinship result; `native` stays absent for the english pack. */
function k(native: string | undefined, en: string, approximate?: boolean): Kinship {
  return {
    ...(native ? { native } : {}),
    en,
    ...(approximate ? { approximate: true } : {}),
  };
}

/** 'పెద్దనాన్న/బాబాయ్'-style either/or when seniority is unrecorded. */
function either(a?: string, b?: string): string | undefined {
  return a && b ? (a === b ? a : `${a}/${b}`) : undefined;
}

// ————————————————— graph walking —————————————————

function parentsOf(data: FamilyData, id: PersonId): PersonId[] {
  const u = parentUnionOf(data, id);
  return u ? (u.partners as PersonId[]) : [];
}

function childrenOf(data: FamilyData, id: PersonId): PersonId[] {
  return unionsAsPartner(data, id).flatMap((u: Union) => u.children);
}

function spousesOf(data: FamilyData, id: PersonId): PersonId[] {
  return unionsAsPartner(data, id)
    .flatMap((u: Union) => u.partners as PersonId[])
    .filter((p) => p !== id);
}

/**
 * Shortest path from `fromId` to `toId`. Blood steps are explored before
 * marriage steps so that, where both exist, we describe someone by blood.
 */
function findPath(data: FamilyData, fromId: PersonId, toId: PersonId): Hop[] | null {
  if (fromId === toId) return [];
  const seen = new Set<PersonId>([fromId]);
  let frontier: Array<{ id: PersonId; path: Hop[] }> = [{ id: fromId, path: [] }];

  for (let depth = 0; depth < MAX_DEPTH; depth += 1) {
    const next: typeof frontier = [];
    for (const node of frontier) {
      const edges: Array<[Step, PersonId[]]> = [
        ['parent', parentsOf(data, node.id)],
        ['child', childrenOf(data, node.id)],
        ['spouse', spousesOf(data, node.id)],
      ];
      for (const [step, ids] of edges) {
        for (const id of ids) {
          if (seen.has(id)) continue;
          const person = data.people[id];
          if (!person) continue;
          const path = [...node.path, { step, person }];
          if (id === toId) return path;
          seen.add(id);
          next.push({ id, path });
        }
      }
    }
    frontier = next;
    if (!frontier.length) break;
  }
  return null;
}

// ————————————————— seniority —————————————————

const male = (p?: Person) => p?.gender === 'm';
const female = (p?: Person) => p?.gender === 'f';

/**
 * A spouse whose gender was never written down is read from their
 * partner's — every marriage this data model records is between two
 * partners, so an in-law badge should never guess wrong just because
 * one field is empty.
 */
function inferSpouseGender(spouse: Person, partner?: Person): Person {
  if (spouse.gender || !partner?.gender) return spouse;
  return { ...spouse, gender: partner.gender === 'm' ? 'f' : 'm' };
}

/**
 * Is `a` older than `b`? Siblings are ordered by their place in the
 * union's children list (recorded eldest-first), which works even when
 * nobody remembers the years. Undefined when the family hasn't said.
 */
function isElder(data: FamilyData, a?: Person, b?: Person): boolean | undefined {
  if (!a || !b) return undefined;
  const ua = parentUnionOf(data, a.id);
  const ub = parentUnionOf(data, b.id);
  if (ua && ub && ua.id === ub.id) {
    const ia = ua.children.indexOf(a.id);
    const ib = ua.children.indexOf(b.id);
    if (ia >= 0 && ib >= 0 && ia !== ib) return ia < ib;
  }
  const ya = a.birth?.gregorian?.slice(0, 4);
  const yb = b.birth?.gregorian?.slice(0, 4);
  if (ya && yb && ya !== yb) return Number(ya) < Number(yb);
  return undefined;
}

// ————————————————— path shape —————————————————

interface Shape {
  up: number;
  down: number;
  hops: Hop[];
  /** Target is married to the blood relative at the end of the path. */
  spouseEnd: boolean;
}

/** Split a path into [spouse] parent^up child^down [spouse]; null if it doesn't fit. */
function shapeOf(path: Hop[]): Shape | null {
  let hops = path;
  let spouseEnd = false;
  if (hops.length && hops[hops.length - 1].step === 'spouse') {
    spouseEnd = true;
    hops = hops.slice(0, -1);
  }
  let up = 0;
  let i = 0;
  while (i < hops.length && hops[i].step === 'parent') {
    up += 1;
    i += 1;
  }
  let down = 0;
  while (i < hops.length && hops[i].step === 'child') {
    down += 1;
    i += 1;
  }
  if (i !== hops.length) return null; // a spouse hop in the middle
  return { up, down, hops, spouseEnd };
}

/** How the blood relative sits relative to the viewer. */
type Klass =
  | 'self'
  | 'parent'
  | 'child'
  | 'sibling'
  | 'cousin'
  | 'uncleAunt'
  | 'nephewNiece'
  | 'grandparent'
  | 'grandchild'
  | 'ancestor'
  | 'descendant'
  | 'distant';

interface Blood {
  klass: Klass;
  /** Paternal side when true, maternal when false, unknown when undefined. */
  paternal?: boolean;
  /** Cousins and nephews: parallel lines are addressed as one's own. */
  parallel?: boolean;
  /** Nephews/nieces: a brother's child when true, a sister's when false. */
  viaBrother?: boolean;
  /**
   * Relative to the viewer (siblings/cousins), to their parent (uncles),
   * or to the sibling whose child this is (nephews).
   */
  elder?: boolean;
  /** Generations away, for the distant cases. */
  degree?: number;
}

function classify(data: FamilyData, viewer: Person, shape: Shape, target: Person): Blood {
  const { up, down, hops } = shape;
  const paternal = up > 0 ? male(hops[0].person) : undefined;

  if (up === 0 && down === 0) return { klass: 'self' };
  if (up === 0) {
    if (down === 1) return { klass: 'child' };
    if (down === 2) return { klass: 'grandchild' };
    return { klass: 'descendant', degree: down };
  }
  if (down === 0) {
    if (up === 1) return { klass: 'parent', paternal };
    if (up === 2) return { klass: 'grandparent', paternal };
    return { klass: 'ancestor', paternal, degree: up };
  }

  const generation = down - up; // negative = older than the viewer

  if (generation === 0) {
    if (up === 1) {
      return { klass: 'sibling', elder: isElder(data, target, viewer) };
    }
    // Cousins: cross or parallel is decided by the two siblings who
    // diverge from the common ancestor.
    const mine = hops[up - 2]?.person;
    const theirs = hops[up]?.person;
    const parallel =
      mine && theirs && mine.gender && theirs.gender
        ? male(mine) === male(theirs)
        : undefined;
    return {
      klass: 'cousin',
      paternal,
      parallel,
      elder: isElder(data, target, viewer),
      degree: up - 1,
    };
  }

  if (generation === -1) {
    // Parent's sibling — or, classificatorily, parent's cousin.
    const myParent = hops[0]?.person;
    return {
      klass: 'uncleAunt',
      paternal,
      elder: isElder(data, target, myParent),
      degree: up - 1,
    };
  }
  if (generation === 1) {
    // Sibling's child — or, classificatorily, cousin's child. Whether
    // the child is cross or one's own (parallel) depends on the
    // sibling at the branch sharing the viewer's gender.
    const sib = hops[hops.length - 2]?.person;
    return {
      klass: 'nephewNiece',
      paternal,
      parallel:
        sib?.gender && viewer.gender ? male(sib) === male(viewer) : undefined,
      viaBrother: sib?.gender ? male(sib) : undefined,
      elder: isElder(data, sib, viewer),
      degree: down - 1,
    };
  }
  // Generation offset alone decides the term: collateral steps never add
  // a "great-". A brother's grandchild is a grandchild, not a
  // great-grandchild.
  if (generation === -2) return { klass: 'grandparent', paternal };
  if (generation === 2) return { klass: 'grandchild' };
  return { klass: 'distant', degree: Math.abs(generation) };
}

// ————————————————— naming —————————————————

function siblingTerm(t: KinshipTerms | undefined, p: Person, elder?: boolean): Kinship {
  if (male(p)) {
    if (elder === true) return k(t?.brotherElder, 'elder brother');
    if (elder === false) return k(t?.brotherYounger, 'younger brother');
    return k(t?.brotherGeneric, 'brother', true);
  }
  if (female(p)) {
    if (elder === true) return k(t?.sisterElder, 'elder sister');
    if (elder === false) return k(t?.sisterYounger, 'younger sister');
    return k(t?.sisterGeneric, 'sister', true);
  }
  return k(t?.siblingGeneric, 'sibling', true);
}

function cousinTerm(t: KinshipTerms | undefined, b: Blood, p: Person): Kinship {
  const far = (b.degree ?? 1) > 1 ? 'second ' : '';
  if (b.parallel === true) {
    const s = siblingTerm(t, p, b.elder);
    return k(s.native, `${far}cousin — addressed as ${s.en}`);
  }
  if (b.parallel === false) {
    if (male(p)) {
      if (b.elder === true) return k(t?.crossCousinMaleElder, `elder ${far}cousin (cross)`);
      if (b.elder === false) return k(t?.crossCousinMaleYounger, `${far}cousin (cross)`);
      return k(either(t?.crossCousinMaleElder, t?.crossCousinMaleYounger), `${far}cousin (cross)`);
    }
    if (female(p))
      return b.elder === true
        ? k(t?.crossCousinFemaleElder, `elder ${far}cousin (cross)`)
        : k(t?.crossCousinFemaleYounger, `${far}cousin (cross)`);
  }
  const s = siblingTerm(t, p, b.elder);
  return k(s.native, `${far}cousin`, true);
}

function uncleAuntTerm(t: KinshipTerms | undefined, b: Blood, p: Person): Kinship {
  const far = (b.degree ?? 1) > 1 ? "parent's cousin — " : '';
  if (b.paternal === true) {
    if (male(p)) {
      if (b.elder === true) return k(t?.fatherElderBrother, `${far}father's elder brother`);
      if (b.elder === false) return k(t?.fatherYoungerBrother, `${far}father's younger brother`);
      return k(either(t?.fatherElderBrother, t?.fatherYoungerBrother), `${far}father's brother`, true);
    }
    return k(t?.fatherSister, `${far}father's sister`);
  }
  if (b.paternal === false) {
    if (male(p)) return k(t?.motherBrother, `${far}mother's brother`);
    if (b.elder === true) return k(t?.motherElderSister, `${far}mother's elder sister`);
    if (b.elder === false) return k(t?.motherYoungerSister, `${far}mother's younger sister`);
    return k(either(t?.motherElderSister, t?.motherYoungerSister), `${far}mother's sister`, true);
  }
  return male(p)
    ? k(either(t?.fatherElderBrother, t?.motherBrother), "parent's brother", true)
    : k(either(t?.fatherSister, t?.motherYoungerSister), "parent's sister", true);
}

function grandparentTerm(t: KinshipTerms | undefined, b: Blood, p: Person): Kinship {
  const great = (b.degree ?? 0) > 0 ? 'great-' : '';
  if (male(p))
    return k(
      great ? t?.greatGrandfather : t?.grandfather,
      `${great}grandfather${b.paternal === undefined ? '' : b.paternal ? " (father's side)" : " (mother's side)"}`,
    );
  if (female(p)) {
    if (great) return k(t?.greatGrandmother, 'great-grandmother');
    return b.paternal === false
      ? k(t?.grandmotherMaternal, "mother's mother")
      : k(t?.grandmotherPaternal, "father's mother");
  }
  return k(t?.grandparentGeneric, `${great}grandparent`, true);
}

function bloodTerm(t: KinshipTerms | undefined, b: Blood, p: Person): Kinship {
  switch (b.klass) {
    case 'self':
      return k(t?.you, 'you');
    case 'parent':
      return male(p) ? k(t?.father, 'father') : k(t?.mother, 'mother');
    case 'child':
      return male(p) ? k(t?.son, 'son') : k(t?.daughter, 'daughter');
    case 'sibling':
      return siblingTerm(t, p, b.elder);
    case 'cousin':
      return cousinTerm(t, b, p);
    case 'uncleAunt':
      return uncleAuntTerm(t, b, p);
    case 'nephewNiece': {
      if (b.parallel === true) {
        // Cross terms are reserved for the cross side; a parallel nephew
        // is classificatorily one's own child, but a bare "son" badge
        // would read as an actual son — name the link instead.
        const sibOf =
          b.viaBrother === true
            ? b.elder === true
              ? t?.ofBrotherElder
              : b.elder === false
                ? t?.ofBrotherYounger
                : t?.ofBrotherGeneric
            : b.elder === true
              ? t?.ofSisterElder
              : b.elder === false
                ? t?.ofSisterYounger
                : t?.ofSisterGeneric;
        const sibEn = b.viaBrother === true ? "brother's" : "sister's";
        if (male(p)) return k(sibOf && t ? `${sibOf} ${t.son}` : undefined, `${sibEn} son`);
        if (female(p)) return k(sibOf && t ? `${sibOf} ${t.daughter}` : undefined, `${sibEn} daughter`);
        return k(sibOf && t ? `${sibOf} ${t.childGeneric}` : undefined, `${sibEn} child`, true);
      }
      return male(p) ? k(t?.crossNephew, 'nephew') : k(t?.crossNiece, 'niece');
    }
    case 'grandparent':
      return grandparentTerm(t, b, p);
    case 'grandchild': {
      const great = (b.degree ?? 0) > 0 ? 'great-' : '';
      if (male(p)) return k(great ? t?.greatGrandson : t?.grandson, `${great}grandson`);
      if (female(p)) return k(great ? t?.greatGranddaughter : t?.granddaughter, `${great}granddaughter`);
      return k(t?.grandchildGeneric, `${great}grandchild`, true);
    }
    case 'ancestor':
      return k(t?.ancestor, `ancestor, ${b.degree} generations up`, true);
    case 'descendant':
      return k(t?.descendant, `descendant, ${b.degree} generations down`, true);
    default:
      return k(t?.relative, 'relative', true);
  }
}

/** The term for someone married to a blood relative. */
function spouseOfTerm(t: KinshipTerms | undefined, b: Blood, spouse: Person): Kinship {
  switch (b.klass) {
    case 'parent':
      return male(spouse)
        ? k(t?.stepFather, "parent's husband", true)
        : k(t?.stepMother, "parent's wife", true);

    case 'uncleAunt': {
      // The spouse of a parent's sibling takes the term of the side they
      // marry into — an aunt by marriage is addressed like an aunt by
      // blood.
      if (b.paternal === true) {
        // Blood relative is on the father's side.
        if (female(spouse)) {
          // Wife of father's brother.
          if (b.elder === true) return k(t?.motherElderSister, "father's elder brother's wife");
          if (b.elder === false) return k(t?.motherYoungerSister, "father's younger brother's wife");
          return k(either(t?.motherElderSister, t?.motherYoungerSister), "father's brother's wife", true);
        }
        return k(t?.motherBrother, "father's sister's husband");
      }
      if (b.paternal === false) {
        if (female(spouse)) return k(t?.fatherSister, "mother's brother's wife");
        if (b.elder === true) return k(t?.fatherElderBrother, "mother's elder sister's husband");
        if (b.elder === false) return k(t?.fatherYoungerBrother, "mother's younger sister's husband");
        return k(either(t?.fatherElderBrother, t?.fatherYoungerBrother), "mother's sister's husband", true);
      }
      return female(spouse)
        ? k(either(t?.fatherSister, t?.motherYoungerSister), "parent's sibling's wife", true)
        : k(either(t?.motherBrother, t?.fatherYoungerBrother), "parent's sibling's husband", true);
    }

    case 'sibling':
    case 'cousin': {
      const kin = b.klass === 'cousin' ? 'cousin' : 'sibling';
      if (female(spouse)) {
        if (b.elder === true)
          return k(t?.siblingWifeElder, `elder ${kin === 'cousin' ? 'cousin' : 'brother'}'s wife`);
        if (b.elder === false)
          return k(t?.siblingWifeYounger, `younger ${kin === 'cousin' ? 'cousin' : 'brother'}'s wife`);
        return k(either(t?.siblingWifeElder, t?.siblingWifeYounger), `${kin}'s wife`, true);
      }
      const husbandEn = `${kin === 'cousin' ? "cousin's" : "sister's"} husband`;
      if (b.elder === true) return k(t?.sisterHusbandElder, husbandEn);
      if (b.elder === false) return k(t?.sisterHusbandYounger, husbandEn);
      return k(either(t?.sisterHusbandElder, t?.sisterHusbandYounger), husbandEn);
    }

    case 'child':
      return male(spouse) ? k(t?.sonInLaw, 'son-in-law') : k(t?.daughterInLaw, 'daughter-in-law');

    case 'nephewNiece': {
      if (b.parallel === true) {
        // A parallel niece counts as a daughter, so her husband is a
        // full son-in-law — not a described-around in-law.
        const sibEn = b.viaBrother === true ? "brother's" : "sister's";
        return male(spouse)
          ? k(t?.sonInLaw, `${sibEn} daughter's husband`)
          : k(t?.daughterInLaw, `${sibEn} son's wife`);
      }
      return male(spouse)
        ? k(t?.nieceHusband, "niece's husband", true)
        : k(t?.nephewWife, "nephew's wife", true);
    }

    case 'grandchild':
      return male(spouse)
        ? k(t?.granddaughterHusband, "granddaughter's husband", true)
        : k(t?.grandsonWife, "grandson's wife", true);

    case 'grandparent':
      return male(spouse)
        ? k(t?.grandfather, "grandparent's husband", true)
        : k(either(t?.grandmotherMaternal, t?.grandmotherPaternal), "grandparent's wife", true);

    default:
      return k(t?.relativeByMarriage, 'relative by marriage', true);
  }
}

/** In-laws reached through the viewer's own spouse. */
function throughSpouseTerm(
  t: KinshipTerms | undefined,
  inner: Kinship,
  target: Person,
  viaBlood: Blood,
  spouse: Person,
): Kinship {
  const whose = male(spouse) ? "husband's" : female(spouse) ? "wife's" : "spouse's";
  if (viaBlood.klass === 'parent') {
    return male(target)
      ? k(t?.spouseFather, `${whose} father`)
      : k(t?.spouseMother, `${whose} mother`);
  }
  if (viaBlood.klass === 'sibling' || viaBlood.klass === 'cousin') {
    // A spouse's cousin is addressed with the sibling-in-law term, but
    // the English gloss should still say which it is.
    const rel = viaBlood.klass === 'cousin' ? 'cousin' : null;
    if (male(target)) {
      if (viaBlood.elder === true)
        return k(t?.spouseBrotherElder, `${whose} elder ${rel ?? 'brother'}`);
      if (viaBlood.elder === false)
        return k(t?.spouseBrotherYounger, `${whose} younger ${rel ?? 'brother'}`);
      return k(t?.spouseBrotherGeneric, `${whose} ${rel ?? 'brother'}`, true);
    }
    if (viaBlood.elder === true)
      return k(t?.spouseSisterElder, `${whose} elder ${rel ?? 'sister'}`);
    if (viaBlood.elder === false)
      return k(t?.spouseSisterYounger, `${whose} younger ${rel ?? 'sister'}`);
    return k(t?.spouseSisterGeneric, `${whose} ${rel ?? 'sister'}`, true);
  }
  // A couple's nephews, nieces and grandchildren are shared — naming the
  // spouse would read as if they kept a separate family. A parallel
  // nephew's gloss names a sibling, though, so it falls through to gain
  // the husband's/wife's prefix — the sibling is the spouse's.
  if (
    viaBlood.klass === 'grandchild' ||
    (viaBlood.klass === 'nephewNiece' && viaBlood.parallel !== true)
  ) {
    return inner;
  }
  // Otherwise: the term your spouse would use, marked as theirs.
  // Glosses are bare noun phrases — the badge supplies the "your".
  return {
    ...(inner.native ? { native: inner.native } : {}),
    en: `${whose} ${inner.en}`,
    ...(inner.approximate ? { approximate: true } : {}),
  };
}

// ————————————————— entry point —————————————————

/** Name the relationship of `target` to `viewer` using a given pack. */
export function kinshipOfWith(
  langPack: LanguagePack,
  data: FamilyData,
  viewerId: PersonId,
  targetId: PersonId,
): Kinship | null {
  const t = langPack.kinship;
  const viewer = data.people[viewerId];
  const target = data.people[targetId];
  if (!viewer || !target) return null;
  if (viewerId === targetId) return k(t?.you, 'you');

  const path = findPath(data, viewerId, targetId);
  if (!path) return null;
  if (path.length === 1 && path[0].step === 'spouse') {
    return male(inferSpouseGender(target, viewer))
      ? k(t?.husband, 'husband')
      : k(t?.wife, 'wife');
  }

  // Reached through the viewer's own spouse: ask how their family sees
  // this person, then express it as an in-law.
  if (path[0].step === 'spouse') {
    const spouse = path[0].person;
    const rest = path.slice(1);
    const innerShape = shapeOf(rest);
    if (innerShape) {
      const bloodPerson = innerShape.spouseEnd
        ? innerShape.hops[innerShape.hops.length - 1]?.person ?? target
        : target;
      const innerBlood = classify(data, spouse, innerShape, bloodPerson);
      const resolved = innerShape.spouseEnd
        ? inferSpouseGender(target, bloodPerson)
        : target;
      const inner = innerShape.spouseEnd
        ? spouseOfTerm(t, innerBlood, resolved)
        : bloodTerm(t, innerBlood, resolved);
      return throughSpouseTerm(t, inner, resolved, innerBlood, inferSpouseGender(spouse, viewer));
    }
    return k(t?.relativeByMarriage, 'relative by marriage', true);
  }

  const shape = shapeOf(path);
  if (!shape) return k(t?.relative, 'relative', true);

  if (shape.spouseEnd) {
    // The person is married to a blood relative; name that relative first.
    const bloodPerson = shape.hops[shape.hops.length - 1]?.person;
    if (!bloodPerson) return k(t?.relative, 'relative', true);
    const blood = classify(data, viewer, shape, bloodPerson);
    return spouseOfTerm(t, blood, inferSpouseGender(target, bloodPerson));
  }

  return bloodTerm(t, classify(data, viewer, shape, target), target);
}

/** Name the relationship of `target` to `viewer` in the configured language. */
export function kinshipOf(
  data: FamilyData,
  viewerId: PersonId,
  targetId: PersonId,
): Kinship | null {
  return kinshipOfWith(activePack, data, viewerId, targetId);
}
